### ISSUE TITLE
Robustness Toolbox: algorithm output schema validation failed

### ISSUE THREAD

**Issue by gang-yi** [aiverify-foundation/aiverify#128]
Hi, I was running the robustness test for tabular dataset (serialised with pickle, pandas version 1.5.3).

As per the suggested [algorithm user inputs](https://imda-btg.github.io/aiverify-developer-tools/stock_plugins/robustness_toolbox/#algorithm-user-inputs), I set the annotated ground truth path to the ground truth dataset (testing dataset), and keyed in "NA" for the name of column containing image file name.
![image](https://github.com/IMDA-BTG/aiverify/assets/70014283/a838c410-cc09-44b0-9516-250f68c06553)

Attached error notification and snippet of log below:
![image](https://github.com/IMDA-BTG/aiverify/assets/70014283/84e7b130-93cc-40cc-95c9-0ae6595adc51)
![image](https://github.com/IMDA-BTG/aiverify/assets/70014283/d6f2dd32-7de8-4b9d-a435-bd40369fb229)

**Comment by imda-kelvinkok** [comment]
Hello. Thanks for your feedback. Can I know what dataset and ground truth dataset are you using, and are you running AI Verify via Docker?

**Comment by kimeetok** [comment]
Hi @gang-yi , apologies we currently support xgboost 1.7.5 and have not tested for 1.1.0, suggest for you to upgrade if possible and try again. [List of supported frameworks](https://imda-btg.github.io/aiverify/others/compatibility/)
As for #135 it has been fixed in our recent v0.9.2 release [here](https://github.com/IMDA-BTG/aiverify/releases/tag/v0.9.2). 
Please try it out and let us know if your issues persist, thank you! :)

**Comment by yschan-ntu** [comment]
Hi @kimeetok, quick check-in to let you know that this issue has not resolved with xgboost 1.7.5. The same error is still showing Error log attached.

[robustness_err_20220810.txt](https://github.com/IMDA-BTG/aiverify/files/12308549/robustness_err_20220810.txt)

**Comment by imda-benedictlee** [comment]
Hi @yschan-ntu and @gang-yi, we have released AI Verify v0.9.3. It should solve the XGBoost Issue. Do give it a try and let us know if it works for you. Thanks!

**Comment by imda-benedictlee** [comment]
Closing this Issue since AI Verify 2.0 is out. Do check it out. If you require additional assistance, feel free to reopen this issue.
